import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/layout/MainLayout";
import TanstackQueryProvider from "@/providers/TanstackQueryProvider";
import { Toaster } from "react-hot-toast";
import AOSInit from "@/components/common/AOSInit";
import { ThemeProvider } from "@/components/features/theme-provider";

const fontManrope= Manrope({
  weight: ["400", "700"],
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ZADA",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${fontManrope.variable} antialiased bg-white dark:bg-[#1D1D24] text-gray-900 dark:text-gray-100 transition-colors duration-300`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <TanstackQueryProvider>
            <AOSInit />
            <Toaster position="top-center" />
            <MainLayout>
              {children}
            </MainLayout>
          </TanstackQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
